# Generated by Django 3.1 on 2020-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputtedPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Images')),
                ('attacks', models.CharField(default='none', max_length=100)),
                ('evolution', models.CharField(blank=True, max_length=100)),
                ('primary_type', models.CharField(choices=[('NORMAL', 'normal'), ('FIRE', 'fire'), ('WATER', 'water'), ('GRASS', 'grass'), ('ELECTRIC', 'electric'), ('ICE', 'ice'), ('FIGHTING', 'fighting'), ('POSION', 'posion'), ('GROUND', 'ground'), ('FLYING', 'flying'), ('PSYHIC', 'psyhic'), ('BUG', 'bug'), ('ROCK', 'rock'), ('GHOST', 'ghost'), ('DARK', 'dark'), ('DRAGON', 'dragon'), ('STEEL', 'steel'), ('FAIRY', 'fairy')], default='normal', max_length=100)),
                ('secondary_type', models.CharField(blank=True, choices=[('NORMAL', 'normal'), ('FIRE', 'fire'), ('WATER', 'water'), ('GRASS', 'grass'), ('ELECTRIC', 'electric'), ('ICE', 'ice'), ('FIGHTING', 'fighting'), ('POSION', 'posion'), ('GROUND', 'ground'), ('FLYING', 'flying'), ('PSYHIC', 'psyhic'), ('BUG', 'bug'), ('ROCK', 'rock'), ('GHOST', 'ghost'), ('DARK', 'dark'), ('DRAGON', 'dragon'), ('STEEL', 'steel'), ('FAIRY', 'fairy')], default='normal', max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
